/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2doproyectoprueba;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author kevda
 */
public class ingreso extends javax.swing.JFrame {

    /**
     * Creates new form ingreso
     */
    public ingreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEntrar)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //usuario nuevoForm = new usuario();
    public String verificarSolicitudes(String nombre)
    {
        this.setVisible(false);
        String respuesta = "";
                File pathFolderMEIA = new File("MEIA");
                String strPath = pathFolderMEIA + "/lista.txt";
                String strError;
                boolean usuarioYPasswordCorrecto = false;
                File ArchivoUsuariosTxt = new File(strPath);
                
                FileReader LecturaArchivo;
                try {
                    LecturaArchivo = new FileReader(ArchivoUsuariosTxt);
                    BufferedReader LeerArchivo = new BufferedReader(LecturaArchivo);
                    String Linea="";
                    try {
                        Linea=LeerArchivo.readLine();
                        String[] split;
                        usuario objUsuarioArchivo = new usuario();
                        if (Linea=="")
                        {
                            // Crear primer usuario de este programa

                            LecturaArchivo.close();
                            LeerArchivo.close();
                        }
                        else
                        {
                            String lineaAEscribir = "";
                            while(Linea != null)
                            {
                                if(Linea!="")
                                {
                                    
                                    split=Linea.split("\\|");
                                    String usuarioComp= nombre;
                                    if(split[1].equals(usuarioComp))
                                    {
                                       if(split[2].equals("1"))
                                       {
                                           respuesta = split[0];
                                       }
                                       else
                                       {
                                           respuesta = "Ninguna";
                                       }
                                            
                                        
                                        
                                    }
                                    
                                }
                                Linea=LeerArchivo.readLine();
                            }  
                        }

                        LecturaArchivo.close();
                        LeerArchivo.close();

                        //listaNombre.setModel(modeloNombre);
                        //listaApellido.setModel(modeloApellido);
                        strError="";
                        //return true;
                        
                        
                        this.setVisible(false);
                        return respuesta;
                    } catch (IOException ex) {
                        strError= ex.getMessage().toString();
                        return respuesta;
                        //return false;
                    }
            } catch (FileNotFoundException ex) {
                strError= ex.getMessage().toString();
                return respuesta;
                //return false;
            }
    }
    public void ingresar()
    {
        this.setVisible(false);
                File pathFolderMEIA = new File("MEIA");
                String strPath = pathFolderMEIA + "/usuario.txt";
                String strError;
                boolean usuarioYPasswordCorrecto = false;
                File ArchivoUsuariosTxt = new File(strPath);
                
                FileReader LecturaArchivo;
                try {
                    LecturaArchivo = new FileReader(ArchivoUsuariosTxt);
                    BufferedReader LeerArchivo = new BufferedReader(LecturaArchivo);
                    String Linea="";
                    try {
                        Linea=LeerArchivo.readLine();
                        String[] split;
                        usuario objUsuarioArchivo = new usuario();
                        if (Linea=="")
                        {
                            // Crear primer usuario de este programa

                            LecturaArchivo.close();
                            LeerArchivo.close();
                        }
                        else
                        {
                            String lineaAEscribir = "";
                            while(Linea != null)
                            {
                                if(Linea!="")
                                {
                                    
                                    split=Linea.split("\\|");
                                    String usuarioComp= jTextField1.getText();
                                    if(split[0].equals(usuarioComp))
                                    {
                                        if(split[1].equals(jTextField2.getText()))
                                        {
                                            usuario nuevoForm = new usuario();
                                            nuevoForm.setVisible(true);
                                            nuevoForm.txtInfo.setText(split[0]);
                                            nuevoForm.txtRecibio.setText(verificarSolicitudes(split[0]));
                                        }
                                        
                                    }
                                    
                                }
                                Linea=LeerArchivo.readLine();
                            }  
                        }

                        LecturaArchivo.close();
                        LeerArchivo.close();

                        //listaNombre.setModel(modeloNombre);
                        //listaApellido.setModel(modeloApellido);
                        strError="";
                        //return true;
                        
                        
                        this.setVisible(false);

                    } catch (IOException ex) {
                        strError= ex.getMessage().toString();
                        //return false;
                    }
            } catch (FileNotFoundException ex) {
                strError= ex.getMessage().toString();
                //return false;
            }
    }
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
         ingresar();
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
