/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2doproyectoprueba;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kevda
 */
public class usuario extends javax.swing.JFrame {

    /**
     * Creates new form usuario
     */
    public usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnviar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        txtRecibio = new javax.swing.JTextField();
        txtInfo = new javax.swing.JTextField();
        btnNegar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnGrupo = new javax.swing.JButton();
        txtGrupo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEnviar.setText("Buscar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnAceptar.setText("✓");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnNegar.setText("X");
        btnNegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegarActionPerformed(evt);
            }
        });

        jLabel1.setText("Solicitud de:");

        btnGrupo.setText("Crear Grupo");
        btnGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupoActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviar)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRecibio, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnGrupo)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNegar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptar)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar))
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRecibio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNegar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrupo)
                    .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void enviarSolicitud(String nombreE,String nombreR)
    {
        File pathFolderMEIA = new File("MEIA");
        String strPath = pathFolderMEIA + "/lista.txt";
        //String[] strCol = {"usuario","nombre","apellido","contraseña","rol","fecha","correo","telefono","path","fotografia","descripcion","estatus"};
        try
        {
        RandomAccessFile filetoUse = new RandomAccessFile(strPath, "rw");
 
        while(filetoUse!= null)
        {
            String linea = filetoUse.readLine();
            String[] str = linea.split("\\|");
            filetoUse.write((nombreE + "|" + nombreR + "|1|0").getBytes());
            
                
        }
        filetoUse.close();
        }
        catch(IOException e){
            e.printStackTrace();
        }
    }
    public boolean confirmar(String nombre)
    {
        File pathFolderMEIA = new File("MEIA");
        String strPath = pathFolderMEIA + "/lista.txt";
        //String[] strCol = {"usuario","nombre","apellido","contraseña","rol","fecha","correo","telefono","path","fotografia","descripcion","estatus"};
        try
        {
        RandomAccessFile filetoUse = new RandomAccessFile(strPath, "rw");
 
        while(filetoUse!= null)
        {
            String linea = filetoUse.readLine();
            String[] str = linea.split("\\|");
            //String parametro = "nombre";
            //String usuario = "sebas10";
            //String original = "Sebastian";
            //String cambiar = "Carlos";
            String lineaCambiada ="";
 
                if(linea.contains(nombre))
                {
                   

                        for(int j = 0; j<4;j++)
                        {
                            if(j == 0)
                            {
                                lineaCambiada += str[j];
                            }
                            else
                            {
                                if(j == 3)
                                {

                                        lineaCambiada += "|" + str[j].replace("0", "1");
                                }
                                else 
                                {
                                    lineaCambiada += "|" + str[j];
                                }

                            }

                        }
                        
                        
                        
                        long suma = linea.length();
                        System.out.println("esto es el largo de la linea" + suma);
                        long position = filetoUse.getFilePointer();   
                        System.out.println("esto devuelve el filepointer" + position);
                        System.out.println("esto devuelve al final: " + (filetoUse.getFilePointer()-(suma+2)));
                        filetoUse.seek(filetoUse.getFilePointer()-(suma+2));
                        
                        filetoUse.write((lineaCambiada + System.getProperty( "line.separator" )).getBytes());
                        return true;
                   
                }
                return false;
                
        }
        filetoUse.close();
        }
        catch(IOException e){
            e.printStackTrace();
        }
        return false;
    }  
    public boolean negar(String nombre)
    {
        File pathFolderMEIA = new File("MEIA");
        String strPath = pathFolderMEIA + "/lista.txt";
        try
        {
        RandomAccessFile filetoUse = new RandomAccessFile(strPath, "rw");
 
        while(filetoUse!= null)
        {
            String linea = filetoUse.readLine();
            String[] str = linea.split("\\|");
            String lineaCambiada ="";
 
                if(linea.contains(nombre))
                {
                        for(int j = 0; j<4;j++)
                        {
                            if(j == 0)
                            {
                                lineaCambiada += str[j];
                            }
                            else
                            {
                                if(j == 2)
                                {
                                        lineaCambiada += "|" + str[j].replace("1", "0");
                                }
                                else 
                                {
                                    lineaCambiada += "|" + str[j];
                                }

                            }

                        }
                        long suma = linea.length();
                        System.out.println("esto es el largo de la linea" + suma);
                        long position = filetoUse.getFilePointer();   
                        System.out.println("esto devuelve el filepointer" + position);
                        System.out.println("esto devuelve al final: " + (filetoUse.getFilePointer()-(suma+2)));
                        filetoUse.seek(filetoUse.getFilePointer()-(suma+2));                       
                        filetoUse.write((lineaCambiada + System.getProperty( "line.separator" )).getBytes());
                        return true;                   
                }
                return false;             
        }
        filetoUse.close();
        }
        catch(IOException e){
            e.printStackTrace();
        }
        return false;
    }  
    public static String calcular(int dv)
    {
        String devol = "";
        for(int i=0;i<=dv;i+=1)
		{
			devol += " ";
		}
        return devol;
    
    }
    
    public void buscar()
    {
        File pathFolderMEIA = new File("MEIA");
        String strPath = pathFolderMEIA + "/usuario.txt";
        String strError;
        String lineaAMostrar = "";
        boolean usuarioYPasswordCorrecto = false;
        File ArchivoUsuariosTxt = new File(strPath);

        FileReader LecturaArchivo;
        try {
            LecturaArchivo = new FileReader(ArchivoUsuariosTxt);
            BufferedReader LeerArchivo = new BufferedReader(LecturaArchivo);
            String linea="";
            try {
                linea =LeerArchivo.readLine();
                String[] str;
                usuario objUsuarioArchivo = new usuario();
                if (linea=="")
                {
                    LecturaArchivo.close();
                    LeerArchivo.close();
                }
                else
                {
                    while(linea != null)
                    {
                        str =linea.split("\\|");
                        if(linea != "")
                        {

                            if(linea.contains(txtBuscar.getText()))
                                {
                                    buscar nuevoForm = new buscar();
                                    nuevoForm.setVisible(true);
                                    nuevoForm.txtNombre.setText(txtBuscar.getText());
                                    nuevoForm.txtEmisor.setText(txtInfo.getText());
                                }
                        }
                        linea = LeerArchivo.readLine();
                    }
                }
            }
            catch (IOException ex) {
                strError= ex.getMessage().toString();
            }
        }
        catch (FileNotFoundException ex) {
        strError= ex.getMessage().toString();
        //return false;
    } 
    }
    private void btnNegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegarActionPerformed
        // TODO add your handling code here:
        if(negar(txtInfo.getText()))
        {
            JOptionPane.showMessageDialog(rootPane, "Se nego la solicitud de amistad");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "No se encontro el archivo");
        }
        
    }//GEN-LAST:event_btnNegarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if(confirmar(txtInfo.getText()))
        {
            JOptionPane.showMessageDialog(rootPane, "Se acepto la solicitud de amistad");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "No se encontro el archivo");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_btnEnviarActionPerformed

    public boolean crearGrupo()
    {
                File Archivo = new File("MEIA/grupo.txt");
        
        if(Archivo.exists()!=true)
        {
            try
            {
                Archivo.createNewFile();
                try (FileWriter Escribir = new FileWriter(Archivo,true)) {
                    Escribir.write((txtInfo.getText() +"|" + txtGrupo.getText() + "|" + txtDescripcion.getText() +"|0|datetime|1") + System.getProperty( "line.separator" ));
                    Escribir.close();                    
                }
                return true;
            }
            catch(IOException ex)
            {
                return false;
            }            
        }
        else
        {   
           //File Archivo = new File(strPath);
            try
            {
                FileWriter Escribir = new FileWriter(Archivo,true);
                BufferedWriter bw = new BufferedWriter(Escribir);
                bw.write(txtInfo.getText() +"|" + txtGrupo.getText() + "|" + txtDescripcion.getText() +"|0|datetime|1" + System.getProperty( "line.separator" ));
                bw.close();
                Escribir.close();
                
                return true;
            }
            catch(IOException ex)
            {
                return false;
            } 
        }
    }
    private void btnGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupoActionPerformed
        // TODO add your handling code here:
        crearGrupo();
        
      
                
    }//GEN-LAST:event_btnGrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnGrupo;
    private javax.swing.JButton btnNegar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtGrupo;
    public static javax.swing.JTextField txtInfo;
    public static javax.swing.JTextField txtRecibio;
    // End of variables declaration//GEN-END:variables
}
